services:
#    profile.example:
#        class: ProfileBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

  profile.form.type:
      class: ProfileBundle\Form\Type\ProfileFormType
      arguments: ["%fos_user.model.user.class%"]
      tags:
          - { name: form.type, alias: fos_user_profile }

  profile.user_creator_api:
      class: ProfileBundle\Services\UserCreatorApi
      arguments: ['@service_container', "@doctrine.orm.entity_manager"]

  profile.listener.request:
      class: ProfileBundle\EventListener\RequestListener
      arguments: [ @service_container ]
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  profile.user_auto_login:
    class: ProfileBundle\Services\UserAutoLogin
    arguments: ['@service_container', "@doctrine.orm.entity_manager"]

  profile.registration_messenger:
    class: ProfileBundle\Services\RegistrationMessenger
    arguments: ['@service_container', "@doctrine.orm.entity_manager"]

  profile.post_persist:
    class: ProfileBundle\EventListener\PostPersistListener
    arguments: [ @service_container ]
    tags:
      - { name: doctrine.event_listener, event: postPersist }