services:
    book.google_search:
        class: BookBundle\Services\GoogleSearch
        arguments: [@service_container, %google_api_key%, %google_project_name%]

    book.shared_shelf_messenger:
        class: BookBundle\Services\SharedShelfMessenger
        arguments: [@service_container]

    book.filter:
        class: BookBundle\Services\BookFilter
        arguments: [@service_container]