imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ProfileBundle/Resources/config/services.yml" }
    - { resource: "@ProfileBundle/Resources/config/config.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

framework:
    #esi:             ~
    translator:
        fallbacks: ["%locale%"]
        paths:
            - '%kernel.root_dir%/../src/ProfileBundle/Resources/translations'
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        gc_probability: 0
        cookie_lifetime: 604800 # 1 week in seconds
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "%kernel.root_dir%/Resources/views/Form/custom_layout.html.twig"
    globals:
        parameters:
            google_api_key: '%google_api_key%'
            site_host: '%host%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
#        auto_mapping: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore
        entity_managers:
            default:
                mappings:
                    SonataMediaBundle: ~
                    ProfileBundle: ~
                    ApplicationSonataMediaBundle: ~
                    BookBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    disable_delivery: false

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        main_css:
            inputs:
                - '%kernel.root_dir%/Resources/public/css/*'
        jquery_and_ui:
            inputs:
                - '%kernel.root_dir%/Resources/public/jquery/jquery.js'
                - '%kernel.root_dir%/Resources/public/jquery/jquery-ui.js'
                - '%kernel.root_dir%/Resources/public/jquery/chosen.jquery.min.js'

        bootstrap:
            inputs:
                - '%kernel.root_dir%/Resources/public/js/moment.min.js'
                - '%kernel.root_dir%/Resources/public/js/transition.js'
                - '%kernel.root_dir%/Resources/public/js/collapse.js'
                - '%kernel.root_dir%/Resources/public/js/z-bootstrap.min.js'
                - '%kernel.root_dir%/Resources/public/js/bootstrap-datetimepicker.min.js'
        main_js:
            inputs:
                - '%kernel.root_dir%/Resources/public/js/*'
                - '@BookBundle/Resources/public/js/*'

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_media:
    db_driver: doctrine_orm # or doctrine_mongodb
    default_context: default
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        shelf:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 350, height: 200, quality: 95, constraint: false}
        profile_avatar:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 200, height: 200, quality: 95, constraint: false}
        book:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 125, height: 190, quality: 95, constraint: false}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false


    providers:
        image:
            resizer: sonata.media.resizer.fixedDimensions
            thumbnail:  sonata.media.thumbnail.format
            filesystem: sonata.media.filesystem.local

parameters:
    sonata.media.provider.image.class: Application\Sonata\MediaBundle\Provider\ImageProvider