social_network:
    resource: "@SocialNetworkBundle/Controller/"
    type:     annotation
    prefix:   /

seo:
    resource: "@AppSeoBundle/Controller/"
    type:     annotation
    prefix:   /

book:
    resource: "@BookBundle/Controller/"
    type:     annotation
    prefix:   /books

app_admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

profile:
    resource: "@ProfileBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
