# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    application.sonata.form.type_extension.media:
        class: Application\Sonata\MediaBundle\Form\Extension\MediaTypeExtension
        tags:
            - {name: form.type_extension, alias: sonata_media_type}

    sonata.media.resizer.fixedDimensions:
        class: Application\Sonata\MediaBundle\Resizer\FixedDimensionsResizer
        arguments: [@sonata.media.adapter.image.gd, 'outbound', @sonata.media.metadata.proxy]

    kernel.listener.user_redirect_listener:
        class: ProfileBundle\EventListener\UserRedirectListener
        arguments: [ @service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.form.data_transformer.book_to_number_transformer:
        class: AppBundle\Form\DataTransformer\BookToNumberTransformer
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    app.form.data_transformer.shelf_to_number_transformer:
        class: AppBundle\Form\DataTransformer\ShelfToNumberTransformer
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    app.form.data_transformer.user_to_number_transformer:
        class: AppBundle\Form\DataTransformer\UserToNumberTransformer
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    app.form.type.share_shelf:
        class: BookBundle\Form\SharedShelfType
        arguments: ['@service_container']
        tags:
            - { name: form.type }

    app.form.type.share_shelf_email:
        class: BookBundle\Form\SharedShelfEmailType
        arguments: ['@service_container']
        tags:
            - { name: form.type }

    app.form.type.entity_hidden:
        class: AppBundle\Form\Extension\Type\EntityHiddenType
        arguments: ["@app.form.data_transformer.book_to_number_transformer"]
        tags:
            - { name: form.type }

    app.file_validatator:
        class: AppBundle\Services\FileValidate
        arguments: ['@service_container']

    app.languages:
        class: AppBundle\Services\Langauges

# Admin entities
    admin.seo_item:
        class: App\AdminBundle\Entity\SeoItem
        arguments: [~, App\SeoBundle\Entity\SeoItem, ~, '@service_container']
        tags:
            - { name: sonata.admin, manager_type: orm, label: SeoItem }