# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    application.sonata.form.type_extension.media:
        class: Application\Sonata\MediaBundle\Form\Extension\MediaTypeExtension
        tags:
            -
                name: form.type_extension
                alias: sonata_media_type
    sonata.media.resizer.fixedDimensions:
            class: Application\Sonata\MediaBundle\Resizer\FixedDimensionsResizer
            arguments: [@sonata.media.adapter.image.gd, 'outbound', @sonata.media.metadata.proxy]
    kernel.listener.user_redirect_listener:
            class: ProfileBundle\EventListener\UserRedirectListener
            arguments: [ @service_container]
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }