<?php

namespace App\SeoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeoItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoItemRepository extends EntityRepository
{
}
