<?php

namespace ProfileBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    const MAX_BEST_READERS = 8;

    /**
     * Get users list sorted by books count
     * @return array
     */
    public function getBestReaders($limit = self::MAX_BEST_READERS){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $queryUsers = $qb->select('u')
            ->select('u')
            ->from('ProfileBundle:User', 'u')
            ->join('u.books', 'b')
            ->addSelect('COUNT(b.id) AS booksCount')
            ->orderBy('booksCount', 'DESC')
            ->groupBy('u.id')
            ->setMaxResults($limit);

        return $queryUsers->getQuery()->getResult();
    }
}
