<?php

namespace BookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReadRepository extends EntityRepository {

    public function getByBook($readId, $book){
        if (!$book) {
            return null;
        }

        return $this->getEntityManager()
            ->getRepository('BookBundle:Read')
            ->findOneBy([
            'id' => $readId,
            'book' => $book
        ]);
    }
}
