<?php

namespace BookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SharedShelfLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharedShelfLinkRepository extends EntityRepository
{
}
