<?php

namespace BookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SharedBookLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharedBookLinkRepository extends EntityRepository
{
}
